version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: idgrow
    ports:
      - "8080:80"  # Laravel akan bisa diakses lewat http://localhost:8080
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
